In [2]:
#https://www.geeksforgeeks.org/implementation-of-logistic-regression-from-scratch-using-python/?ref=rp
from sklearn import datasets
from sklearn.datasets import fetch_openml
#split the data set
from sklearn.model_selection import train_test_split
#to create the combination
from sklearn import metrics
import numpy as np
import matplotlib.pyplot as plt
import math

In [3]:
iris = datasets.load_iris()

In [53]:
X = iris.data
y = (iris.target !=0) *1
#y = iris.target[:-50] 
print(X)
print(y)
y.shape, X.shape

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

((150,), (150, 4))

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((135, 4), (135,), (15, 4), (15,))

In [55]:
class LoggisticRegression():
    
    def __init__(self, learningRate, iterations):
        self.learningRate = learningRate
        self.iterations = iterations
        
    def fit(self, X,y):
        self.sample_rows, self.sample_feature  = X.shape
        self.w = np.zeros(self.sample_feature)
        self.b = 0
        self.X = X
        self.y = y
        
        for i in range(self.iterations):
            y_predicted = 1/(1+np.exp(-(self.X.dot(self.w)+self.b)))
            #calculating gradient descent 
            temp = (y_predicted-self.y.T)
            temp = np.reshape(temp, self.sample_rows)
            w_gradient= np.dot(self.X.T, temp)/self.sample_rows
            b_gradient= np.sum(temp)/self.sample_rows
            
            #updating weights
            self.w = self.w - self.learningRate*w_gradient
            self.b = self.b - self.learningRate*b_gradient
            
            return self
    def predict(self, X):
        sigmoid = 1/(1+np.exp(-(X.dot(self.w)+self.b)))
        y = np.where(sigmoid > 0.5,1,0)
        return y
            
            
            

In [56]:
logiReg = LoggisticRegression(learningRate = 0.01, iterations=100 )
logiReg.fit(X_train, y_train)
y_prediction = logiReg.predict(X_test)

def getAccuracy(y_new, y_p):
    return np.sum(y_new==y_p) / len(y_new)

print("Accuracy is:",getAccuracy(y_test,y_prediction))

Accuracy is: 0.8
